"""Backward-compatible re-exports of ``aeon.errors``.

Prefer importing from ``aeon.errors`` in new code. This module remains so
existing ``from aeon.facade.api import …`` call sites keep working.
"""

from aeon.errors import (
    AeonError,
    ContractViolationError,
    CoreInvalidApplicationError,
    CoreSubtypingError,
    CoreTypeApplicationRequiresBareTypesError,
    CoreTypeCheckingError,
    CoreTypingRelation,
    CoreVariableNotInContext,
    CoreWellformnessError,
    CoreWrongKindInTypeApplicationError,
    ErasedUsedAtRuntimeError,
    InstanceResolutionError,
    LinearBranchMismatchError,
    LinearTypeNotBoundLinearlyError,
    LinearUnusedError,
    LinearUsedTooManyTimesError,
    LinearityError,
    LiquidTypeCheckingFailedRelation,
    MethodResolutionError,
    ModuleNotFoundAeonError,
    NonOrderableComparisonError,
    RefinementExecutionHoleError,
    TypeClassError,
    UndecidableRefinementError,
    UnificationFailedError,
    UnificationKindError,
    UnificationSubtypingError,
    UnificationUnknownTypeError,
    UnreachablePatternError,
    UnknownDecoratorError,
)

__all__ = [
    "AeonError",
    "ContractViolationError",
    "CoreInvalidApplicationError",
    "CoreSubtypingError",
    "CoreTypeApplicationRequiresBareTypesError",
    "CoreTypeCheckingError",
    "CoreTypingRelation",
    "CoreVariableNotInContext",
    "CoreWellformnessError",
    "CoreWrongKindInTypeApplicationError",
    "ErasedUsedAtRuntimeError",
    "InstanceResolutionError",
    "LinearBranchMismatchError",
    "LinearTypeNotBoundLinearlyError",
    "LinearUnusedError",
    "LinearUsedTooManyTimesError",
    "LinearityError",
    "LiquidTypeCheckingFailedRelation",
    "MethodResolutionError",
    "ModuleNotFoundAeonError",
    "NonOrderableComparisonError",
    "RefinementExecutionHoleError",
    "TypeClassError",
    "UndecidableRefinementError",
    "UnificationFailedError",
    "UnificationKindError",
    "UnificationSubtypingError",
    "UnificationUnknownTypeError",
    "UnreachablePatternError",
    "UnknownDecoratorError",
]
