#!/bin/bash
# export PATH="$PATH:/usr/bin/z3-4.8.5.9c9cd5ebf791-x86-ubuntu-14.04/bin/"
export PYTHONPATH="$PYTHONPATH:/usr/bin/"

OUTPUTDIR="bin"
for i in "$@"
do
case $i in
    --outputdir=*)
	    OUTPUTDIR="${i#*=}"
	   # shift # past argument=value
	    ;;
    *)
          # unknown option
    ;;
esac
done

function prepare_java_sources {
   cp java/src/* $OUTPUTDIR/ && cp java/lib/* $OUTPUTDIR/
   rm -rf $OUTPUTDIR/*.class
   cd $OUTPUTDIR/ && javac -Xdiags:verbose -cp .:AeminiumRuntime.jar {A,D,F,GP,J,R,P,Box,IntList}.java && cd ..
}

function clean_code {
   java -jar tools/google-java-format-1.3-all-deps.jar --replace $OUTPUTDIR/E.java
}

function compile_code {
   cd $OUTPUTDIR && javac -Xdiags:verbose -cp .:AeminiumRuntime.jar E.java && cd ..
}

function run_code {
   cd $OUTPUTDIR && java -cp .:AeminiumRuntime.jar E && cd ..
}

mkdir -p $OUTPUTDIR &&
prepare_java_sources &&
python3.7 -m aeon2 $@ &&
clean_code &&
compile_code &&
run_code
