#!/bin/bash

python3 -m src $@ && cp java/src/* bin/ && cp java/lib/* bin/  && cd bin/ && java -jar ../tools/google-java-format-1.3-all-deps.jar --replace E.java && rm -rf *.class && javac -Xdiags:verbose -cp AeminiumRuntime.jar {A,J,F,E}.java && java -cp .:AeminiumRuntime.jar E && cd ..
