native Math.abs : (_:Float) -> _:Float
native Math.abs : (_:Double) -> _:Double
native Math.abs : (_:Integer) -> _:Integer
native Math.abs : (_:Long) -> _:Long
native Math.sin : (_:Double) -> _:Double
native Math.cos : (_:Double) -> _:Double
native Math.tan : (_:Double) -> _:Double
native Math.atan2 : (_:Double,_:Double) -> _:Double
native Math.sqrt : (_:Double) -> _:Double
native Math.log : (_:Double) -> _:Double
native Math.log10 : (_:Double) -> _:Double
native Math.pow : (_:Double,_:Double) -> _:Double
native Math.exp : (_:Double) -> _:Double
native Math.min : (_:Integer,_:Integer) -> _:Integer
native Math.min : (_:Long,_:Long) -> _:Long
native Math.min : (_:Float,_:Float) -> _:Float
native Math.min : (_:Double,_:Double) -> _:Double
native Math.max : (_:Float,_:Float) -> _:Float
native Math.max : (_:Long,_:Long) -> _:Long
native Math.max : (_:Integer,_:Integer) -> _:Integer
native Math.max : (_:Double,_:Double) -> _:Double
native Math.addExact : (_:Long,_:Long) -> _:Long
native Math.addExact : (_:Integer,_:Integer) -> _:Integer
native Math.decrementExact : (_:Integer) -> _:Integer
native Math.decrementExact : (_:Long) -> _:Long
native Math.incrementExact : (_:Integer) -> _:Integer
native Math.incrementExact : (_:Long) -> _:Long
native Math.multiplyExact : (_:Integer,_:Integer) -> _:Integer
native Math.multiplyExact : (_:Long,_:Long) -> _:Long
native Math.multiplyExact : (_:Long,_:Integer) -> _:Long
native Math.negateExact : (_:Integer) -> _:Integer
native Math.negateExact : (_:Long) -> _:Long
native Math.subtractExact : (_:Long,_:Long) -> _:Long
native Math.subtractExact : (_:Integer,_:Integer) -> _:Integer
native Math.fma : (_:Float,_:Float,_:Float) -> _:Float
native Math.fma : (_:Double,_:Double,_:Double) -> _:Double
native Math.scalb : (_:Float,_:Integer) -> _:Float
native Math.scalb : (_:Double,_:Integer) -> _:Double
native Math.copySign : (_:Float,_:Float) -> _:Float
native Math.copySign : (_:Double,_:Double) -> _:Double
native Math.getExponent : (_:Double) -> _:Integer
native Math.getExponent : (_:Float) -> _:Integer
native Math.signum : (_:Double) -> _:Double
native Math.signum : (_:Float) -> _:Float
native Math.asin : (_:Double) -> _:Double
native Math.acos : (_:Double) -> _:Double
native Math.atan : (_:Double) -> _:Double
native Math.toRadians : (_:Double) -> _:Double
native Math.toDegrees : (_:Double) -> _:Double
native Math.cbrt : (_:Double) -> _:Double
native Math.IEEEremainder : (_:Double,_:Double) -> _:Double
native Math.ceil : (_:Double) -> _:Double
native Math.floor : (_:Double) -> _:Double
native Math.rint : (_:Double) -> _:Double
native Math.round : (_:Double) -> _:Long
native Math.round : (_:Float) -> _:Integer
native Math.random : () -> _:Double
native Math.toIntExact : (_:Long) -> _:Integer
native Math.multiplyFull : (_:Integer,_:Integer) -> _:Long
native Math.multiplyHigh : (_:Long,_:Long) -> _:Long
native Math.floorDiv : (_:Long,_:Integer) -> _:Long
native Math.floorDiv : (_:Integer,_:Integer) -> _:Integer
native Math.floorDiv : (_:Long,_:Long) -> _:Long
native Math.floorMod : (_:Integer,_:Integer) -> _:Integer
native Math.floorMod : (_:Long,_:Integer) -> _:Integer
native Math.floorMod : (_:Long,_:Long) -> _:Long
native Math.ulp : (_:Float) -> _:Float
native Math.ulp : (_:Double) -> _:Double
native Math.sinh : (_:Double) -> _:Double
native Math.cosh : (_:Double) -> _:Double
native Math.tanh : (_:Double) -> _:Double
native Math.hypot : (_:Double,_:Double) -> _:Double
native Math.expm1 : (_:Double) -> _:Double
native Math.log1p : (_:Double) -> _:Double
native Math.nextAfter : (_:Float,_:Double) -> _:Float
native Math.nextAfter : (_:Double,_:Double) -> _:Double
native Math.nextUp : (_:Double) -> _:Double
native Math.nextUp : (_:Float) -> _:Float
native Math.nextDown : (_:Double) -> _:Double
native Math.nextDown : (_:Float) -> _:Float
native Math.powerOfTwoD : (_:Integer) -> _:Double
native Math.powerOfTwoF : (_:Integer) -> _:Float
