#!/usr/bin/env python3
"""Generate a PAPER-SIZE (32x32 = 1024-pixel) inverse-CSG FTA example.

This is the exact-refinement encoding of csg_fta_exhaustive.ae, but at the
resolution of Feser, Dillig & Solar-Lezama "Metric Program Synthesis for Inverse
CSG" (arXiv:2206.06164): a 32x32 bitmap == 1024 boolean I/O examples, one per
pixel. Every constructor's refined return type therefore pins `pixel` on all
1024 cells (two implication clauses each for Rect; one OR / AND-NOT pair each
for Union / Diff), so the file is ~half a megabyte of refinement.

It exists to make the scalability wall concrete: the ENCODING is identical to
the 3x3 toy, but at 1024 pixels z3 must discharge ~1000-conjunct VCs per
candidate and FTA must enumerate Rect over a 32-wide coordinate range
(32**4 ~ 1e6 tuples), which is exactly what the paper's metric/approximate
method (the `symetric` backend) is designed to avoid.

    python examples/synthesis/fta/gen_csg32.py > examples/synthesis/fta/csg_paper_32.ae

RESULT (the point of this file): the generated 483 KB program does NOT even
typecheck. Each constructor's refinement is a ~2048-deep right-nested `&&`
AST; walking it exceeds aeon's recursion limit (10000, set in __main__) and
raises RecursionError after ~35 s -- before synthesis is ever attempted.
Lifting that limit only exposes the deeper walls (z3 on 1024-conjunct VCs;
FTA enumerating 32**4 Rect tuples). The 3x3 toys are the regime where exact
per-pixel-refinement FTA is feasible; the paper's 32x32 needs the metric
backend, which the examples/synthesis/csg/ benchmarks already use.
"""

from __future__ import annotations

N = 32  # 32x32 grid -> 1024 pixels == the paper's 1024 I/O examples


def code(i: int, j: int) -> int:
    return i * N + j


# ---- reference program (defines the target bitmap) -----------------------
# A thick frame: Diff (Rect 6 6 25 25) (Rect 11 11 20 20).
def rect_set(x1, y1, x2, y2):
    return {code(i, j) for i in range(N) for j in range(N) if x1 <= i <= x2 and y1 <= j <= y2}


REF = "Diff (Rect 6 6 25 25) (Rect 11 11 20 20)"
TARGET = rect_set(6, 6, 25, 25) - rect_set(11, 11, 20, 20)


def cells():
    return [(i, j) for i in range(N) for j in range(N)]


def rect_refinement():
    parts = []
    for i, j in cells():
        box = f"((x1 <= {i} && {i} <= x2) && (y1 <= {j} && {j} <= y2))"
        parts.append(f"({box} --> pixel s {i} {j} == 1)")
        parts.append(f"(!{box} --> pixel s {i} {j} == 0)")
    return "\n    && ".join(parts)


def union_refinement():
    parts = []
    for i, j in cells():
        parts.append(f"((pixel p {i} {j} == 1 || pixel q {i} {j} == 1) --> pixel s {i} {j} == 1)")
        parts.append(f"((pixel p {i} {j} == 0 && pixel q {i} {j} == 0) --> pixel s {i} {j} == 0)")
    return "\n    && ".join(parts)


def diff_refinement():
    parts = []
    for i, j in cells():
        cond = f"(pixel p {i} {j} == 1 && pixel q {i} {j} == 0)"
        parts.append(f"({cond} --> pixel s {i} {j} == 1)")
        parts.append(f"(!{cond} --> pixel s {i} {j} == 0)")
    return "\n    && ".join(parts)


def target_refinement():
    parts = []
    for i, j in cells():
        parts.append(f"pixel s {i} {j} == {1 if code(i, j) in TARGET else 0}")
    return "\n    && ".join(parts)


print(f"""# PAPER-SIZE (32x32 = 1024 pixels) inverse-CSG via FTA, generated by gen_csg32.py.
# Bitmap encoded as 1024 per-pixel refinements over an uninterpreted `pixel`
# (== the paper's contains(e,x,y), arXiv:2206.06164). Reference: {REF}.
# Each constructor pins `pixel` on all 1024 cells. This is the 3x3 toy at the
# paper's resolution -- it exists to exhibit the scalability wall (z3 on
# ~1000-conjunct VCs; FTA enumerating Rect over 32**4 coordinate tuples).
import Array;

def pixel : (s:(Array Int)) -> (x:Int) -> (y:Int) -> Int = uninterpreted

def Rect (x1:Int) (y1:Int) (x2:Int) (y2:Int) : {{ s:(Array Int) |
       {rect_refinement()}
  }} = native "[i*{N}+j for i in range(max(0,x1),min({N},x2+1)) for j in range(max(0,y1),min({N},y2+1))]"

def Union (p:(Array Int)) (q:(Array Int)) : {{ s:(Array Int) |
       {union_refinement()}
  }} = native "p + q"

def Diff (p:(Array Int)) (q:(Array Int)) : {{ s:(Array Int) |
       {diff_refinement()}
  }} = native "[x for x in p if x not in q]"

# Target = bitmap of {REF}  ({len(TARGET)} of {N * N} pixels on).
def shape : {{ s:(Array Int) |
       {target_refinement()}
  }} = ?hole;
""")
