#!/usr/bin/env python3
"""Generate AeonDoc HTML for every stdlib library and an index page.

Used by the docs CI workflow to produce ``docs/stdlib/*.html`` so the Jekyll
site published to GitHub Pages can include the standard-library reference.

Run locally with::

    uv run python scripts/build_stdlib_docs.py

By default it generates into ``docs/stdlib/`` relative to the repo root.
Pass a directory as the first argument to override the destination::

    uv run python scripts/build_stdlib_docs.py path/to/output/dir
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

from aeon.documentation import generate_documentation


REPO_ROOT = Path(__file__).resolve().parent.parent
LIBRARIES_DIR = REPO_ROOT / "aeon" / "libraries"


def _display_path(p: Path) -> str:
    """Like ``Path.relative_to(REPO_ROOT)`` but falls back to the absolute path
    when ``p`` lives outside the repo (e.g. an out-of-tree ``out_dir``)."""
    try:
        return str(p.relative_to(REPO_ROOT))
    except ValueError:
        return str(p)


def build_module_pages(out_dir: Path) -> list[str]:
    """Generate one HTML page per stdlib module. Returns sorted module names."""
    out_dir.mkdir(parents=True, exist_ok=True)
    names: list[str] = []
    for src in sorted(LIBRARIES_DIR.glob("*.ae")):
        out_path = out_dir / f"{src.stem}.html"
        generate_documentation(str(src), str(out_path))
        names.append(src.stem)
        print(f"  {_display_path(src)} -> {_display_path(out_path)}")
    return names


def build_index(out_dir: Path, names: list[str]) -> None:
    """Write a small ``index.html`` listing every generated module page."""
    items = "\n".join(f'        <li><a href="{html.escape(n)}.html">{html.escape(n)}</a></li>' for n in names)
    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aeon Standard Library</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        ul {{ list-style: none; padding: 0; }}
        li {{ padding: 6px 0; font-family: 'Courier New', monospace; }}
        a {{ color: #2980b9; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        p {{ color: #555; margin-bottom: 18px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Aeon Standard Library</h1>
        <p>HTML reference for the modules under <code>libraries/</code>, generated by
        <code>python -m aeon --doc</code>. Each page lists the module's types, constructors,
        functions, and uninterpreted declarations.</p>
        <ul>
{items}
        </ul>
    </div>
</body>
</html>
"""
    (out_dir / "index.html").write_text(index_html, encoding="utf-8")
    print(f"  index -> {_display_path(out_dir / 'index.html')}")


def main(argv: list[str]) -> int:
    out_dir = Path(argv[1]) if len(argv) > 1 else REPO_ROOT / "docs" / "stdlib"
    print(f"Generating stdlib HTML docs into {out_dir}")
    names = build_module_pages(out_dir)
    build_index(out_dir, names)
    print(f"Done: {len(names)} modules + index.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
