"""Generate an Aeon local-robustness query for a trained ReLU digit classifier.

Trains a small fully-connected ReLU network on scikit-learn's 8x8 ``digits``
dataset (a real handwritten-digit task, no download), then emits a ``.ae``
file that encodes the network as exact scalar ``Certify.relu`` units and asks
the type checker to prove local robustness around one test image:

    for all x with ||x - x0||_inf <= eps,  logit[true] - logit[runner_up] > 0

Type-checking the emitted file *is* the robustness proof. The point is to
measure how this exact-SMT approach scales as the network (hidden width,
input dimension) grows.

Usage:
    python gen.py --hidden 8 --downsample 2 --eps 0.02 --sample 0 > out.ae

Knobs:
    --hidden       hidden-layer width (number of ReLU neurons)
    --downsample   k: average-pool the 8x8 image by kxk -> (8/k)^2 inputs
                   (1 -> 64 inputs, 2 -> 16, 4 -> 4)
    --eps          L-infinity radius in normalized [0,1] pixel space
    --sample       index of the test image to certify
    --pairs        'hardest' (default; true vs runner-up) or 'all'
                   (emit one def per competing class -> full robustness)
"""

from __future__ import annotations

import argparse

import numpy as np
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier


def pool(images: np.ndarray, k: int) -> np.ndarray:
    """Average-pool a stack of 8x8 images by k x k -> (8//k)^2 features."""
    if k == 1:
        return images.reshape(len(images), -1)
    s = 8 // k
    out = images.reshape(len(images), s, k, s, k).mean(axis=(2, 4))
    return out.reshape(len(images), -1)


def fnum(x: float) -> str:
    """Aeon-safe float literal: wrap negatives as ``(0.0 - m)``."""
    x = float(x)
    if x < 0:
        return f"(0.0 - {-x:.8f})"
    return f"{x:.8f}"


def affine(coefs: np.ndarray, bias: float, var: str, n: int) -> str:
    """Left-nested, fully-parenthesised ``bias + sum_i coef_i * var_i``."""
    expr = fnum(bias)
    for i in range(n):
        expr = f"({expr} + ({fnum(coefs[i])} * {var}{i}))"
    return expr


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hidden", type=int, default=8)
    ap.add_argument("--downsample", type=int, default=2)
    ap.add_argument("--eps", type=float, default=0.02)
    ap.add_argument("--sample", type=int, default=0)
    ap.add_argument("--pairs", choices=["hardest", "all"], default="hardest")
    args = ap.parse_args()

    digits = load_digits()
    X = pool(digits.images, args.downsample) / 16.0  # normalize to [0,1]
    y = digits.target
    n_in = X.shape[1]

    # Deterministic split + train.
    rng = np.random.RandomState(0)
    perm = rng.permutation(len(X))
    X, y = X[perm], y[perm]
    n_test = 300
    Xtr, ytr = X[:-n_test], y[:-n_test]
    Xte, yte = X[-n_test:], y[-n_test:]

    clf = MLPClassifier(
        hidden_layer_sizes=(args.hidden,),
        activation="relu",
        max_iter=500,
        random_state=0,
    )
    clf.fit(Xtr, ytr)
    acc = clf.score(Xte, yte)

    W1, b1 = clf.coefs_[0], clf.intercepts_[0]  # (n_in, H), (H,)
    W2, b2 = clf.coefs_[1], clf.intercepts_[1]  # (H, n_out), (n_out,)
    H = args.hidden

    x0 = Xte[args.sample]
    logits0 = W2.T @ np.maximum(0.0, W1.T @ x0 + b1) + b2
    true_c = int(np.argmax(logits0))
    order = np.argsort(logits0)[::-1]
    runner = int(order[1])

    lines: list[str] = []
    lines.append("# AUTO-GENERATED by examples/nn/mnist/gen.py — do not edit.")
    lines.append(
        f"# digits {int(np.sqrt(n_in))}x{int(np.sqrt(n_in))} ({n_in} inputs), "
        f"hidden={H}, eps={args.eps}, sample={args.sample}"
    )
    lines.append(
        f"# test accuracy={acc:.3f}, predicted class={true_c}, "
        f"runner-up={runner}, nominal margin={logits0[true_c] - logits0[runner]:.4f}"
    )
    lines.append("#")
    lines.append("# Type-checking this file proves: for every input in the L-inf")
    lines.append(f"# eps-ball around test image #{args.sample}, the network's logit for")
    lines.append(f"# class {true_c} stays strictly above the competing class(es).")
    lines.append("")
    lines.append("open Certify")
    lines.append("")

    # Input box: clamp [x0 - eps, x0 + eps] to [0,1].
    arglines = []
    for i in range(n_in):
        lo = max(0.0, float(x0[i]) - args.eps)
        hi = min(1.0, float(x0[i]) + args.eps)
        arglines.append(f"    (x{i}: {{v: Float | {fnum(lo)} <= v && v <= {fnum(hi)}}})")

    competitors = [j for j in range(W2.shape[1]) if j != true_c]
    if args.pairs == "hardest":
        competitors = [runner]

    for j in competitors:
        name = f"robust_{true_c}_vs_{j}"
        lines.append(f"# Margin of class {true_c} over class {j} (> 0 == robust).")
        lines.append(f"def {name}")
        lines.extend(f"{a}" for a in arglines)
        lines.append("     :")
        lines.append("    {margin: Float | margin > 0.0} =")
        # hidden ReLU units
        for h in range(H):
            pre = affine(W1[:, h], b1[h], "x", n_in)
            lines.append(f"    let h{h} = relu ({pre}) in")
        # output margin true_c - j as affine over hidden units
        diff_w = W2[:, true_c] - W2[:, j]
        diff_b = b2[true_c] - b2[j]
        margin = affine(diff_w, diff_b, "h", H)
        lines.append(f"    {margin} ;")
        lines.append("")

    lines.append("def main (_: Int) : Unit = print 0")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
