"""Emit a *flattened* linear-relaxation robustness query that actually scales.

Profiling the naive per-neuron relaxation (relax_gen.py) showed the cost was
NOT ReLU case-splitting and NOT a lack of opacity -- Aeon already lowers each
``let h = e`` to an opaque SMT variable ``forall h. h == e -> ...``. The cost
was the *nesting depth* of that chain: with one binding per neuron the VC
translator re-traverses the accumulated context combinatorially (translate_liq
was called ~40k times per equation). Width drove the blow-up.

The fix is to thread as few bindings as possible. For a single hidden layer
the network is, region by region, affine: a *stable* ReLU (pre-activation
interval entirely >=0 or <=0) is just identity or zero, so its contribution
folds directly into the output as a constant + linear term. Only *unstable*
ReLUs (interval straddling 0) need the triangle relaxation, and only those
become ``let`` bindings. Nesting depth becomes the number of unstable neurons
-- typically a small fraction of the width, especially for small eps -- so
verification scales with the genuinely-nonlinear part of the network, not its
total size.

Soundness is unchanged (the triangle bounds are the same; the stable folds
are exact). Completeness is unchanged from relax_gen.py.

Usage:
    python relax_flat_gen.py --hidden 128 --downsample 1 --eps 0.02 > q.ae
"""

from __future__ import annotations

import argparse

import numpy as np
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier


def pool(images: np.ndarray, k: int) -> np.ndarray:
    if k == 1:
        return images.reshape(len(images), -1)
    s = 8 // k
    return images.reshape(len(images), s, k, s, k).mean(axis=(2, 4)).reshape(len(images), -1)


def fnum(x: float) -> str:
    x = float(x)
    return f"(0.0 - {-x:.8f})" if x < 0 else f"{x:.8f}"


def affine_terms(base: str, coefs, names) -> str:
    """Left-nested ``base + sum_i coef_i * name_i`` (skips zero coefficients)."""
    expr = base
    for c, nm in zip(coefs, names):
        if abs(float(c)) > 1e-12:
            expr = f"({expr} + ({fnum(c)} * {nm}))"
    return expr


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hidden", type=int, default=64)
    ap.add_argument("--downsample", type=int, default=1)
    ap.add_argument("--eps", type=float, default=0.02)
    ap.add_argument("--sample", type=int, default=0)
    args = ap.parse_args()

    digits = load_digits()
    X = pool(digits.images, args.downsample) / 16.0
    y = digits.target
    n = X.shape[1]
    rng = np.random.RandomState(0)
    perm = rng.permutation(len(X))
    X, y = X[perm], y[perm]
    Xtr, ytr, Xte = X[:-300], y[:-300], X[-300:]
    clf = MLPClassifier(hidden_layer_sizes=(args.hidden,), activation="relu", max_iter=500, random_state=0).fit(
        Xtr, ytr
    )
    acc = clf.score(X[-300:], y[-300:])
    W1, b1 = clf.coefs_[0], clf.intercepts_[0]
    W2, b2 = clf.coefs_[1], clf.intercepts_[1]
    H = args.hidden
    x0 = Xte[args.sample]
    lg = W2.T @ np.maximum(0.0, W1.T @ x0 + b1) + b2
    c = int(np.argmax(lg))
    r = int(np.argsort(lg)[::-1][1])

    lo = np.maximum(0.0, x0 - args.eps)
    hi = np.minimum(1.0, x0 + args.eps)
    pos, neg = np.maximum(W1, 0.0), np.minimum(W1, 0.0)
    z_lo = b1 + pos.T @ lo + neg.T @ hi
    z_hi = b1 + pos.T @ hi + neg.T @ lo

    dw = W2[:, c] - W2[:, r]  # margin weights over hidden units
    db = b2[c] - b2[r]

    active = z_lo >= 0
    inactive = z_hi <= 0
    unstable = ~active & ~inactive

    # Fold the stable neurons' exact contribution into a single affine form:
    #   active  j: relu(z_j) = z_j = b1[j] + W1[:,j]·x   -> contributes dw_j * z_j
    #   inactive j: relu(z_j) = 0                         -> contributes nothing
    eff_b = db + float(np.sum(dw[active] * b1[active]))
    eff_w = W1[:, active] @ dw[active]  # length-n input coefficients

    L = []
    L.append("# AUTO-GENERATED by examples/nn/mnist/relax_flat_gen.py — do not edit.")
    L.append(
        f"# digits {int(np.sqrt(n))}x{int(np.sqrt(n))} ({n} inputs), hidden={H}, eps={args.eps}, sample={args.sample}"
    )
    L.append(f"# acc={acc:.3f}, class={c} vs runner-up={r}, nominal margin={lg[c] - lg[r]:.4f}")
    L.append(
        f"# ReLUs: {int(active.sum())} active + {int(inactive.sum())} inactive "
        f"= {int(active.sum() + inactive.sum())} stable folded into the affine form; "
        f"{int(unstable.sum())} unstable kept as bindings"
    )
    L.append("# Flattened: binding depth = #unstable, not width -> scales.")
    L.append("")
    L.append("open Relax")
    L.append("")
    L.append(f"def robust_{c}_vs_{r}")
    for i in range(n):
        L.append(f"    (x{i}: {{v: Float | {fnum(lo[i])} <= v && v <= {fnum(hi[i])}}})")
    L.append("     :")
    L.append("    {margin: Float | margin > 0.0} =")

    # One binding per unstable neuron (the only nonlinear part).
    uidx = [j for j in range(H) if unstable[j]]
    for j in uidx:
        a = z_hi[j] / (z_hi[j] - z_lo[j])
        bb = -z_hi[j] * z_lo[j] / (z_hi[j] - z_lo[j])
        z = affine_terms(fnum(b1[j]), W1[:, j], [f"x{i}" for i in range(n)])
        L.append(f"    let h{j} = relu_relaxed {fnum(a)} {fnum(bb)} ({z}) in")

    # margin = (folded affine over inputs) + sum over unstable of dw_j * h_j
    expr = affine_terms(fnum(eff_b), eff_w, [f"x{i}" for i in range(n)])
    expr = affine_terms(expr, [dw[j] for j in uidx], [f"h{j}" for j in uidx])
    L.append(f"    {expr} ;")
    L.append("")
    L.append("def main (_: Int) : Unit = print 0")
    print("\n".join(L))


if __name__ == "__main__":
    main()
