"""Emit a *linear-relaxation* (DeepPoly/CROWN-style) robustness query.

Same setup as ``gen.py`` (train a one-hidden-layer ReLU net on 8x8 digits,
certify local robustness around a test image), but instead of encoding each
ReLU exactly with ``Certify.relu`` (disjunction -> case split -> exponential),
it encodes each ReLU with its convex triangle relaxation via ``Relax`` --
pure linear bounds, no case split. z3 then verifies in linear real arithmetic
and scales polynomially.

Per neuron, with pre-activation interval [l, u] (exact for one hidden layer,
since the pre-activation is affine over the input box):
  * l >= 0  -> ReLU is identity: bind the affine expression directly (exact).
  * u <= 0  -> ReLU is zero: bind 0 (exact).
  * l < 0 < u (unstable) -> bind ``relu_relaxed a b z`` with the triangle
        a = u / (u - l),  b = -u*l / (u - l).

Soundness: a relaxed proof is a genuine robustness guarantee. Incompleteness:
a failure is inconclusive (the relaxation may be too loose) -- the classic
DeepPoly/CROWN trade-off. (Multi-layer nets would compound looseness unless
the [l,u] are tightened by DeepPoly back-substitution; this prototype does
the exact single-layer concretization and notes the extension.)

Usage:
    python relax_gen.py --hidden 32 --downsample 4 --eps 0.02 > q.ae
"""

from __future__ import annotations

import argparse

import numpy as np
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier


def pool(images: np.ndarray, k: int) -> np.ndarray:
    if k == 1:
        return images.reshape(len(images), -1)
    s = 8 // k
    return images.reshape(len(images), s, k, s, k).mean(axis=(2, 4)).reshape(len(images), -1)


def fnum(x: float) -> str:
    x = float(x)
    return f"(0.0 - {-x:.8f})" if x < 0 else f"{x:.8f}"


def affine(coefs: np.ndarray, bias: float, var: str, n: int) -> str:
    expr = fnum(bias)
    for i in range(n):
        expr = f"({expr} + ({fnum(coefs[i])} * {var}{i}))"
    return expr


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hidden", type=int, default=32)
    ap.add_argument("--downsample", type=int, default=4)
    ap.add_argument("--eps", type=float, default=0.02)
    ap.add_argument("--sample", type=int, default=0)
    args = ap.parse_args()

    digits = load_digits()
    X = pool(digits.images, args.downsample) / 16.0
    y = digits.target
    n_in = X.shape[1]

    rng = np.random.RandomState(0)
    perm = rng.permutation(len(X))
    X, y = X[perm], y[perm]
    Xtr, ytr, Xte = X[:-300], y[:-300], X[-300:]

    clf = MLPClassifier(hidden_layer_sizes=(args.hidden,), activation="relu", max_iter=500, random_state=0)
    clf.fit(Xtr, ytr)
    acc = clf.score(X[-300:], y[-300:])

    W1, b1 = clf.coefs_[0], clf.intercepts_[0]
    W2, b2 = clf.coefs_[1], clf.intercepts_[1]
    H = args.hidden
    x0 = Xte[args.sample]

    logits0 = W2.T @ np.maximum(0.0, W1.T @ x0 + b1) + b2
    true_c = int(np.argmax(logits0))
    runner = int(np.argsort(logits0)[::-1][1])

    # Input box, clamped to [0,1].
    lo = np.maximum(0.0, x0 - args.eps)
    hi = np.minimum(1.0, x0 + args.eps)

    # Per-neuron pre-activation interval [l,u] over the box (exact: affine
    # over a box -> pick the box corner per weight sign).
    pos, neg = np.maximum(W1, 0.0), np.minimum(W1, 0.0)
    z_lo = b1 + pos.T @ lo + neg.T @ hi  # (H,)
    z_hi = b1 + pos.T @ hi + neg.T @ lo
    n_stable = int(np.sum((z_lo >= 0) | (z_hi <= 0)))
    n_unstable = H - n_stable

    L = []
    L.append("# AUTO-GENERATED by examples/nn/mnist/relax_gen.py — do not edit.")
    L.append(
        f"# digits {int(np.sqrt(n_in))}x{int(np.sqrt(n_in))} ({n_in} inputs), "
        f"hidden={H}, eps={args.eps}, sample={args.sample}"
    )
    L.append(
        f"# acc={acc:.3f}, class={true_c} vs runner-up={runner}, nominal margin={logits0[true_c] - logits0[runner]:.4f}"
    )
    L.append(f"# ReLUs: {n_stable} stable (exact), {n_unstable} unstable (triangle-relaxed)")
    L.append("# Linear-relaxation encoding: no case splits -> z3 stays in linear arithmetic.")
    L.append("")
    L.append("open Relax")
    L.append("")
    L.append(f"def robust_{true_c}_vs_{runner}")
    for i in range(n_in):
        L.append(f"    (x{i}: {{v: Float | {fnum(lo[i])} <= v && v <= {fnum(hi[i])}}})")
    L.append("     :")
    L.append("    {margin: Float | margin > 0.0} =")
    for j in range(H):
        z = affine(W1[:, j], b1[j], "x", n_in)
        lj, uj = z_lo[j], z_hi[j]
        if lj >= 0:  # stable active: identity
            L.append(f"    let h{j} = {z} in")
        elif uj <= 0:  # stable inactive: zero
            L.append(f"    let h{j} = 0.0 in")
        else:  # unstable: triangle relaxation
            a = uj / (uj - lj)
            b = -uj * lj / (uj - lj)
            L.append(f"    let h{j} = relu_relaxed {fnum(a)} {fnum(b)} ({z}) in")
    diff_w = W2[:, true_c] - W2[:, runner]
    diff_b = b2[true_c] - b2[runner]
    L.append(f"    {affine(diff_w, diff_b, 'h', H)} ;")
    L.append("")
    L.append("def main (_: Int) : Unit = print 0")
    print("\n".join(L))


if __name__ == "__main__":
    main()
